image_width: 640
image_height: 480
camera_name: narrow_stereo/left
camera_matrix:
  rows: 3
  cols: 3
  data: [309.56828,   0.     , 323.04952,
           0.     , 307.53082, 233.54293,
           0.     ,   0.     ,   1.     ]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [-0.291153, 0.065396, 0.002461, -0.000651, 0.000000]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1., 0., 0.,
         0., 1., 0.,
         0., 0., 1.]
projection_matrix:
  rows: 3
  cols: 4
  data: [219.2526 ,   0.     , 321.33228,   0.     ,
           0.     , 237.86399, 233.18969,   0.     ,
           0.     ,   0.     ,   1.     ,   0.     ]
